# Generated by Django 2.2.1 on 2019-05-25 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gridview.Gender')),
            ],
        ),
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bond_level', models.IntegerField(default=0)),
                ('bondee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bondee', to='gridview.Person')),
                ('bonder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonder', to='gridview.Person')),
            ],
        ),
    ]
